* Supporting Our Projects

The Software Freedom Conservancy is dedicated to the cause of Free
and Open Source Software. Some of our member projects use a license
such as the GNU General Public license, which has a reciprocal
agreement to pass along changes made using the same terms as the
original license, while other project use more permissive licenses,
such as the Apache license, which does not have the same
requirements. Each project is free to choose the license that they
feel fits their project, and Conservancy works to defend that choice
by ensuring that each of our projects' licenses are adhered to.

In FY2013, Conservancy welcomed phpMyAdmin, BuildBot and
OpenTripPlanner to its list of member projects, meaning that each of
these projects will gain the benefit of Conservancy status, including
license enforcement.

As an example of the type of enforcement that Conservancy
occassionally needs to engage in, in August of 2013, Conservancy's GPL
Compliance Project for Linux Developers project announced its role in
assisting Samsung with a GPL compliance issue related to the Linux
kernel and the exFAT filesystem driver. Conservancy is proud to
announce that this issue was able to be resolved collaboratively with
Samsung. 

Conservancy stands behind the Free/Open Source Software community and
is pleased that we could represent our member project and come to a
positive conclusion in this matter.
