* New Member Projects

Three new projects joined Conservancy in 2013, phpMyAdmin, Buildbot
and OpenTripPlanner.

phpMyAdmin provides a Free and Open Source web interface for several
popular database platforms, including MySQL, MariaDB and
Drizzle. phpMyAdmin has been adopted by theousands of web hosting
companies around the world. Learn more about phpMyAdmin at
http://phpmyadmin.net


Buildbot is a continuous integration tool that automates the
build/test/release cycle that developers have to perform so
often. Using Builtbot saves developers time and energy by providing a
clean, easy and automated way to compile their software, run it
through automated tests and finally package it up for others to
use. You can learn more about BuildBot at http://buildbot.net

OpenTripPlanner is a Free/Open Source software for transportation
routing. OTP can provide directions using for car, bike, walking,
trains and buses for a municipality. It can even do large scale
network analysis and prediction modeling, allowing for simulations
which can be used for design or emergency preparedness. Learn more
about OpenTripPlanner at http://opentripplanner.org

* Mifos Initiative

Usually, Conservancy aims to be a project's long term home, but in
the case of the Mifos Initiativw, we planned its graduation from the
beginning, and are proud to say that this project has grown up and
left the nest. 

* Evergreen Conference

The Evergreen project held its 5th annual conference in Vancouver,
British Columbia from April 10-13, 2013. The conference featured a
developer hackfest, several interest group meetings, and two tracks of
programs, one aimed at end users and another aimed at technical users
and developers.

* Releases

The Evergreen project announced two major releases - 2.4 and 2.5 -
during FY13. The releases featured a responsive design for Evergreen’s
public catalog, the ability for users to self-register for a library
account, and many workflow improvements and new features for library
staff using Evergreen.

* Hack-a-way

The Evergreen project held a developer hack-a-way in Grand Rapids,
Michigan in September 2013. During the hack-a-way, developers made big
steps in building a more responsive public web catalog, specifically
with support for more mobile devices in mind. The developer community
also began plans to move Evergreen from a XULRunner-based application
to a web application.
