* New Member Projects

Three new projects joined Conservancy in FY2013:  phpMyAdmin, Buildbot
and OpenTripPlanner.

phpMyAdmin provides a Free and Open Source web interface for several
popular database platforms, including MySQL, MariaDB and
Drizzle. phpMyAdmin has been adopted by theousands of web hosting
companies around the world. Learn more about phpMyAdmin at
http://phpmyadmin.net

Buildbot is a continuous integration tool that automates the
build/test/release cycle that developers have to perform so
often. Using Builtbot saves developers time and energy by providing a
clean, easy and automated way to compile their software, run it
through automated tests and finally package it up for others to
use. You can learn more about BuildBot at http://buildbot.net

OpenTripPlanner is a Free/Open Source software for transportation
routing. OTP can provide directions using for car, bike, walking,
trains and buses for a municipality. It can even do large scale
network analysis and prediction modeling, allowing for simulations
which can be used for design or emergency preparedness. Learn more
about OpenTripPlanner at http://opentripplanner.org

* Conservancy Launches NPO Accounting Initiative

In May 2013, Conservancy launched our NPO Accounting Initiative, an effort 
to spearhead the development of a user-friendly accounting system for non-
profit organizations based solely on FLOSS.  Our dream is to offer 
non-profits a viable FLOSS alternative, and to enable the charitable sector 
to reallocate millions of dollars currently spent on propietary accounting 
software back towards program activities that benefit the public.  
Recognizing that this will be a multi-year initiative, given our resources, 
we launched a fundraiser to fund our work.  As a result, we were able to 
successfully complete an initial survey of existing FLOSS systems designed 
for for-profit accounting to determine which codebase, if any, was suitable 
to serve as the foundation for our initiative.  

We're currently looking to raise additional money to launch a coordinated 
FLOSS development effort to create a system for all non-profits to use.  
Resources permitting, our next step will be to improve the FLOSS system
selected in the initial phase to create a basic accounting system suitable 
for small-to-medium sized USA-based non-profit organizations -- including 
fiscal sponsors like Conservancy.  For more information about Conservancy's
NPO Accounting initiative, visit https://sfconservancy.org/npoacct/.

* Conservancy and COSM Announce Mifos Initiative

Mifos is an award-winning software project built around providing
financial services to the poor. In February 2012, Conservancy
assumed stewardship of the project. At the same time, Mifos project
leaders started their own public charity, the Community for Open
Source Microfinance (COSM), with the intent of growing COSM into a
home for Mifos and other related program activities.  Conservancy served
as Mifos' fiscal sponsor for nineteen months, and we shared our nonprofit
and FLOSS community-building expertise with COSM's founders during their
organization's early days.

We are happy to report that in September of 2013, COSM reached a point
of maturity and Conservancy and COSM worked together to transfer
stewardship to the COSM organization, which has subsequently renamed
itself the Mifos Initiative to match its flagship
project. Conservancy is honored to have played a role in both Mifos
and the Mifos Initiative's development.

* Conservancy Conferences

The Evergreen project, which maintains a popular integrated library hosting 
software platform, held its 5th annual conference in Vancouver, British 
Columbia on April 10-13, 2013. The conference featured a developer 
hackfest, several interest group meetings, and two tracks of programs, one 
aimed at end users and another aimed at technical users and developers.

On May 12-17, 2013, the Boost project, maintainers of portable C++ 
libraries, hosted C++ Now 2013, a conference focusing on discussion and 
education about open source software usage relating to C++. The conference,
held in Aspen, Colorado, featured presentations from many of the leading 
developers in the C++ community.  

The Selenium project, maintainers of a automated browser testing software
suite, hosted Selenium Conference 2013 in Boston, Massachusetts on June 10-
12, 2013.  SeConf '13 was Selenium's largest conference yet, attracting
over 500 attendees from all over the world to network, attend workshops,
and learn more about the project. 


