* Evergreen Conference

The Evergreen project held its 5th annual conference in Vancouver,
British Columbia from April 10-13, 2013. The conference featured a
developer hackfest, several interest group meetings, and two tracks of
programs, one aimed at end users and another aimed at technical users
and developers.

* Releases

The Evergreen project announced two major releases - 2.4 and 2.5 -
during FY13. The releases featured a responsive design for Evergreen’s
public catalog, the ability for users to self-register for a library
account, and many workflow improvements and new features for library
staff using Evergreen.

* Hack-a-way

The Evergreen project held a developer hack-a-way in Grand Rapids,
Michigan in September 2013. During the hack-a-way, developers made big
steps in building a more responsive public web catalog, specifically
with support for more mobile devices in mind. The developer community
also began plans to move Evergreen from a XULRunner-based application
to a web application.
