* Conservancy's Member Projects Commitments to Students

Once again, Conservancy's member projects have shown their commitment
to diversity and outreach through involvement with student
participation programs such as Google Summer of Code, which encourages
student involved in Free and Open Source software development, as well
as C++Now, which encourages involvement in the C++ community. Boost,
Buildbot and Inkscape all participated in Google Summer of Code, with
well over twenty students participating. Boost also participated in
C++Now, with seven students across 5 countries. Conservancy supports
these efforts to bring students into our member projects, as well as
the greater Free and Open Source software community.

* Boost

Boost is a C++ library collection that contains algorithms for many
types of applications. Boost lies at the core of many Free and Open
Source software programs. In 2013, Boost released two new versions of
their software and included features such as a new Asynchronous File
I/O library as well as extensions to many of their existing libraries.

* Buildbot

Buildbot is a continuous integration software for the automation of
the compile/test/deployment process involved in software development.
In August of 2013, Buildbot released a new version of their software
(release 0.8.8) which added a number of bug fixes, general
improvements, and allowed for software developers to more easily
automate their development process.

* Darcs

Darcs is an Open Source, cross platform version control system that
focuses on changes, rather than snapshots, which allows for a freer
and more streamlined approach to version control.

In 2013, the Darcs team announced the Darcsden project, an Open Source
repository hosting platform for Darcs, written in Haskell. It
currently offers several features like authentication from
Github/OpenID, password recovery, online repository file editing, and
comparisons between a repository and its forks.

* Evergreen

The Evergreen project announced two major releases - 2.4 and 2.5 -
during FY2013. These new releases featured a responsive
design for Evergreen’s public catalog, the ability for users to
self-register for a library account, and many workflow improvements
and new features for library staff using Evergreen.

* Inkscape

Inkscape is an Open Source vector graphics editor similar to Adobe
Illustrator or Corel Draw. What sets Inkscape apart is its use of
Scalable Vector Graphics (SVG) as its native format. In FY2013, Inkscape
made significant improvements to the security, stability and
functionality of its software including improvements to its CAD
support, document template support, vectorizing pixelized images and
improvements to the visual elements of the software.

* phpMyAdmin

phpMyAdmin is a web interface to several popular database systems
including mySQL, MariaDB and Drizzle. In 2013, Conservancy welcomed
phpMyAdmin to its list of sponsored projects. They also released a new
version of their software which included a significant improvement to
their web interface.

* Squeak

Squeak is a full featured programming environment based on the
Smalltalk programming language. In 2013 Scratch made a number of
improvements to its design to allow it to run more easily on low
powered devices such as the Raspberry Pi, OPLC or PIC
microcontrollers. By focusing on small, low powered devices, Scratch
will be better able to work in educational environments with embedded
processors or robots.

* Sugar Labs

The Sugar Learning Platform promotes collaborative learning through
the use of Free/Libre Software tools. Designed from the ground up
especially for children, Sugar's estimated three million users
worldwide are offered an alternative to traditional “office-desktop”
software.

In 2013, Sugar Labs made strides in making JavaScript/HTML5 a first
class programming environment while continuing to work closely with
the Fedora and GNOME upstream communities. Over 30% of the patches in
their newest release come directly from Sugar users: the children
themselves.

* SWIG

SWIG is a software development tool that connects programs written in
low level languages like C and C++ with a variety of high-level
programming languages such as as Javascript, Perl, PHP, Python, Tcl
and Ruby. In 2013 the SWIG team released version 3.0.0, which included
better C++ support, support for the new C++11 standard as well as
nested classes.

* Wine

Wine is a Windows emulator, allowing Windows software to run on other
platforms such as GNU/Linux and Apple Macs. In July of 2013, after
sixteen months of development, Wine released version 1.6, which
included a large number of changes including better Mono (.NET)
support, better support for the Apple Mac, and significantly improved
support for new application and games.
